### ISSUE TITLE
Recommended way to install in github actions

### ISSUE THREAD

**Issue by schpet** [samphippen/rubyfmt#495]
i'm interested in ensuring my code is formatted with rubyfmt, and i understand that i need to ask other contributors to install rubyfmt from homebrew or the release page here. maybe i can simplify it for them by providing a Brewfile, i just have to worry about differing versions with that.

but for a project on github, is there a recommended way of setting up github actions yaml? unclear if i should `brew install` it or grab a release with some shell script, if i can cache all this somehow, so thought i'd pose the question here in case anyone has a good strategy.

i'm such a huge fan of the way this thing formats ruby, i hope to use this in more projects.

**Comment by reese** [comment]
The question of making sure a bunch of developers all have the right version is probably fairly dependent on the specifics of your project I think, there's a bunch of different approaches there. (Happy to chat more about that if you want, but it's a bit tangential to getting things set up in an action.)

I think the shortest answer is probably to use `brew`, it's basically a one-liner to setup. If you need caching, I think you can always just cache the homebrew directory, but installing from brew in these actions is quite fast and you may not even need it. You can always pull the release binary but then you have to either set it up in your PATH or write a bunch of scripts that point to the right binary etc., which is probably more effort than it's worth.

**Comment by schpet** [comment]
cool thanks for weighing in! and yeah versioning i don't really care about so everyone can just get on board with latest. this seems to work:

```yaml
jobs:
  rubyfmt:
    runs-on: ubuntu-latest
    steps:
    - uses: Homebrew/actions/setup-homebrew@master
    - uses: actions/checkout@v4
    - name: Install rubyfmt
      run: brew install rubyfmt
    - name: Check formatting
      run: rubyfmt --check .

```
